# Starter pipeline
name: 2.7.2.$(rev:r)
variables: 
- name: Project.Path
  value: '**/PolyhydraGames.Discogs.csproj'
- name: Project.Test
  value: '**/DiscogsClient.Test.csproj'
- name: BuildConfiguration
  value: Release
trigger:
  branches:
    include:
    - refs/heads/master
  paths:
    include:
    - DiscogsClient


jobs:
- job: Phase_1 
  cancelTimeoutInMinutes: 1
  pool:
    name: Default
  steps:
  - checkout: self

  - task: DotNetCoreCLI@2
    displayName: dotnet test
    enabled: false
    inputs:
      command: test
      projects: $(Project.Test) 
      arguments: '--collect "XPlat Code coverage;;Format=cobertura,opencover"'
  - task: PublishCodeCoverageResults@2
    enabled: false
    inputs:
      summaryFileLocation: '$(Agent.TempDirectory)/**/*cobertura.xml'
      #coverage.opencover.xml
      pathToSources: 'DiscogsClient'
      failIfCoverageEmpty: true  

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: '$(Project.Path)'      
      arguments: '--configuration Release' 

  - task: DotNetCoreCLI@2
    displayName: dotnet pack
    inputs:
      command: pack 
      packagesToPack: 
      versioningScheme: 'byBuildNumber'      
      arguments: '--no-build'



  - task: NuGetCommand@2
    displayName: NuGet push
    inputs:
      command: push
      feedPublish: 015fc12f-cd63-4ab4-8d6a-dc889e53bf70
      allowPackageConflicts: true
  - task: ado-discord-webhook@1
    inputs:
      channelId: '1083779130576879656'
      webhookKey: 'QAhq2PpBl9iUSv51rQNPajpVZivOdj-hMcClCwHBz7OFdyxuI9Ni_Ykvglpxw53oDX9D'
      name: 'Polyhydra Build'
      avatar: 'https://scontent-iad3-1.xx.fbcdn.net/v/t39.30808-6/277759422_459407522643032_5740191239763665615_n.png?_nc_cat=109&ccb=1-7&_nc_sid=09cbfe&_nc_ohc=Eh7rt73EuYcAX-1w6EJ&_nc_ht=scontent-iad3-1.xx&oh=00_AfA8K4k2WtaqlaA0CEznY-Hk2DZY3gsdDwPp-XOw3L1B3Q&oe=64121C61'
      messageType: 'content'
      content: 'Discogs Completed Build: $(Build.BuildNumber)'